export enum EnumTagColor {
    TAG_COLOR_SLATE = "TAG_COLOR_SLATE",
    TAG_COLOR_GRAY = "TAG_COLOR_GRAY",
    TAG_COLOR_ZINC = "TAG_COLOR_ZINC",
    TAG_COLOR_NEUTRAL = "TAG_COLOR_NEUTRAL",
    TAG_COLOR_STONE = "TAG_COLOR_STONE",
    TAG_COLOR_RED = "TAG_COLOR_RED",
    TAG_COLOR_ORANGE = "TAG_COLOR_ORANGE",
    TAG_COLOR_AMBER = "TAG_COLOR_AMBER",
    TAG_COLOR_YELLOW = "TAG_COLOR_YELLOW",
    TAG_COLOR_LIME = "TAG_COLOR_LIME",
    TAG_COLOR_GREEN = "TAG_COLOR_GREEN",
    TAG_COLOR_ESMERALD = "TAG_COLOR_ESMERALD",
    TAG_COLOR_TEAL = "TAG_COLOR_TEAL",
    TAG_COLOR_CYAN = "TAG_COLOR_CYAN",
    TAG_COLOR_SKY = "TAG_COLOR_SKY",
    TAG_COLOR_BLUE = "TAG_COLOR_BLUE",
    TAG_COLOR_INDIGO = "TAG_COLOR_INDIGO",
    TAG_COLOR_VIOLET = "TAG_COLOR_VIOLET",
    TAG_COLOR_PURPLE = "TAG_COLOR_PURPLE",
    TAG_COLOR_FUCHSIA = "TAG_COLOR_FUCHSIA",
    TAG_COLOR_PINK = "TAG_COLOR_PINK",
    TAG_COLOR_ROSE = "TAG_COLOR_ROSE"
}
export enum EnumStatusColor {
    STATUS_COLOR_SLATE = "STATUS_COLOR_SLATE",
    STATUS_COLOR_GRAY = "STATUS_COLOR_GRAY",
    STATUS_COLOR_ZINC = "STATUS_COLOR_ZINC",
    STATUS_COLOR_NEUTRAL = "STATUS_COLOR_NEUTRAL",
    STATUS_COLOR_STONE = "STATUS_COLOR_STONE",
    STATUS_COLOR_RED = "STATUS_COLOR_RED",
    STATUS_COLOR_ORANGE = "STATUS_COLOR_ORANGE",
    STATUS_COLOR_AMBER = "STATUS_COLOR_AMBER",
    STATUS_COLOR_YELLOW = "STATUS_COLOR_YELLOW",
    STATUS_COLOR_LIME = "STATUS_COLOR_LIME",
    STATUS_COLOR_GREEN = "STATUS_COLOR_GREEN",
    STATUS_COLOR_ESMERALD = "STATUS_COLOR_ESMERALD",
    STATUS_COLOR_TEAL = "STATUS_COLOR_TEAL",
    STATUS_COLOR_CYAN = "STATUS_COLOR_CYAN",
    STATUS_COLOR_SKY = "STATUS_COLOR_SKY",
    STATUS_COLOR_BLUE = "STATUS_COLOR_BLUE",
    STATUS_COLOR_INDIGO = "STATUS_COLOR_INDIGO",
    STATUS_COLOR_VIOLET = "STATUS_COLOR_VIOLET",
    STATUS_COLOR_PURPLE = "STATUS_COLOR_PURPLE",
    STATUS_COLOR_FUCHSIA = "STATUS_COLOR_FUCHSIA",
    STATUS_COLOR_PINK = "STATUS_COLOR_PINK",
    STATUS_COLOR_ROSE = "STATUS_COLOR_ROSE"
}
export enum EnumTaskPriority {
    TASK_PRIORITY_NONE = "TASK_PRIORITY_NONE",
    TASK_PRIORITY_LOW = "TASK_PRIORITY_LOW",
    TASK_PRIORITY_MEDIUM = "TASK_PRIORITY_MEDIUM",
    TASK_PRIORITY_HIGH = "TASK_PRIORITY_HIGH",
    TASK_PRIORITY_URGENT = "TASK_PRIORITY_URGENT"
}
export enum EnumRole {
    ROLE_DEVELOPER = "ROLE_DEVELOPER",
    ROLE_MANEGER = "ROLE_MANEGER",
    ROLE_TESTER = "ROLE_TESTER",
    ROLE_PRODUCT_OWNER = "ROLE_PRODUCT_OWNER",
    ROLE_SCRUM_MASTER = "ROLE_SCRUM_MASTER",
}
export enum EnumInvite {
    INVITE_NONE = "INVITE_NONE",
    INVITE_PENDING = "INVITE_PENDING",
    INVITE_ACCEPTED = "INVITE_ACCEPTED",
    INVITE_DECLINED = "INVITE_DECLINED",
    INVITE_REMOVED = "INVITE_REMOVED",
}
export enum EnumStatusCategory {
    STATUS_CATEGORY_BACKLOG = "STATUS_CATEGORY_BACKLOG",
    STATUS_CATEGORY_UNSTARTED = "STATUS_CATEGORY_UNSTARTED",
    STATUS_CATEGORY_STARTED = "STATUS_CATEGORY_STARTED",
    STATUS_CATEGORY_COMPLETED = "STATUS_CATEGORY_COMPLETED",
    STATUS_CATEGORY_CANCELLED = "STATUS_CATEGORY_CANCELLED",
}
export enum EnumProjecEstimative {
    PROJECT_ESTIMATIVE_FIBONACCI = "PROJECT_ESTIMATIVE_FIBONACCI",
    PROJECT_ESTIMATIVE_LINEAR = "PROJECT_ESTIMATIVE_LINEAR",
    PROJECT_ESTIMATIVE_SQUARES = "PROJECT_ESTIMATIVE_SQUARES",
    PROJECT_ESTIMATIVE_TSHIRT = "PROJECT_ESTIMATIVE_TSHIRT",
    PROJECT_ESTIMATIVE_EASY_HARD = "PROJECT_ESTIMATIVE_EASY_HARD"
}
export enum EnumStatusHistory {
    STATUS_HISTORY_ACTIVE = "STATUS_HISTORY_ACTIVE",
    STATUS_HISTORY_PENDING = "STATUS_HISTORY_PENDING",
    STATUS_HISTORY_CANCELLED = "STATUS_HISTORY_CANCELLED",
}
export enum EnumStatusSprint {
    STATUS_SPRINT_NOT_STARTED = "STATUS_SPRINT_NOT_STARTED",
    STATUS_SPRINT_STARTED = "STATUS_SPRINT_STARTED",
    STATUS_SPRINT_CLOSED = "STATUS_SPRINT_CLOSED"
}

export interface CollaborationUpdateEvent {
    originUserId: string;
    projectId: string;
    entityType: 'PROJECT' | 'TASK' | 'STATUS' | 'SPRINT' | 'HISTORY' | 'TAG' | 'RELATION_USER_PROJECT' | 'ADD_ATTACHMENT' | 'REMOVE_ATTACHMENT' | 'ADD_USER' | 'REMOVE_USER' | 'ADD_TAG' | 'REMOVE_TAG' | 'ADD_SPRINT' | 'REMOVE_SPRINT' | 'ADD_HISTORY' | 'REMOVE_HISTORY';
    action: 'UPDATE' | 'CREATE' | 'DELETE';
    entityId: string;
    data: Record<string, any>;
  }

export interface ErrorResponse {
    details: string
    error: string
    message: string
    path: string
    status: string
    statusCode: number
    timestamp: string
}